Make student_list.py and write read_exam and show_student_list
shoishizaki/exam-app pull request #1
Opened 2019-04-30 17:10 UTC by shoishizaki

書いているときにこれはmainの動きでは無いなと思ったのでファイル名をstudent_list.pyに変更しました。読み込み用のfunctionと出力用のfunctionを作ったので確認お願いします。

2019-04-30 17:20 UTC, ryotogashi commented on student_list.py
> +
@shoishizaki 不必要な改行は消しましょう。
以下を参照して見てください。
https://www.yokoyan.net/entry/2018/06/29/181500

2019-04-30 17:22 UTC, ryotogashi commented
@shoishizaki システムは基本的にmainから始まります。始まりを作成して見ましょう。

2019-04-30 17:25 UTC, ryonryon requested changes

2019-04-30 17:25 UTC, ryotogashi commented on student_list.py
> +            self.student_list.append(st)
👍

2019-04-30 17:25 UTC, ryotogashi commented on student_list.py
> +        self.read_exam()
@shoishizaki show_student_listを呼び出すたびにself.read_examを呼び出すと生徒の情報が被ってしまわないですか？

2019-04-30 17:26 UTC, ryotogashi commented
@shoishizaki 全体的によくできていると思います。EmployeeListの応用でStudentListを作成できたのはとても良いと思います。

2019-05-01 02:13 UTC, shoishizaki commented on student_list.py
> +        self.read_exam()
きちんとできているか確認するときに入れたcodeを消すのを忘れていました。

2019-05-01 16:12 UTC, shoishizaki reviewed
main.pyを作りました。エラーは起きないのですが、うまくシステムが動きません。理由がわからないので、確認お願いします。

2019-05-02 05:37 UTC, ryotogashi commented on main.py
> +        stu = student_list.Student_list()
@shoishizaki 変数名をわかりやすく変更してみましょう。studentなのかstudente_listなのかが区別できるとなおいいですね。

2019-05-02 05:41 UTC, ryotogashi commented on student_list.py
> +
@shoishizaki 不要ライン

2019-05-03 00:15 UTC, ryonryon approved these changes
👍

2019-05-03 01:23 UTC, merged